CREATE SCHEMA `content_store` ;

CREATE TABLE FILE_METADATA(
  FILE_ID BIGINT NOT NULL AUTO_INCREMENT,
  STORAGE_ID VARCHAR(100) NOT NULL,
  FILE_NAME VARCHAR(200) NOT NULL,
  APPLICATION_NAME VARCHAR(50) NOT NULL,
  CONTENT_LENGTH BIGINT NOT NULL,
  CONTENT_TYPE VARCHAR(30) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (FILE_ID)
);

CREATE TABLE FILE_VERSION(
  VERSION_ID BIGINT NOT NULL AUTO_INCREMENT,
  FILE_ID BIGINT NOT NULL,
  STORAGE_ID VARCHAR(100) NOT NULL,
  FILE_NAME VARCHAR(200) NOT NULL,
  APPLICATION_NAME VARCHAR(50) NOT NULL,
  CONTENT_LENGTH BIGINT NOT NULL,
  CONTENT_TYPE VARCHAR(30) NOT NULL,
  FILE_CREATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (VERSION_ID)
);


CREATE TABLE FILE_ARCHIVE(
  ARCHIVE_ID BIGINT NOT NULL AUTO_INCREMENT,
  FILE_ID BIGINT NOT NULL,
  STORAGE_ID VARCHAR(100) NOT NULL,
  FILE_NAME VARCHAR(200) NOT NULL,
  APPLICATION_NAME VARCHAR(50) NOT NULL,
  CONTENT_LENGTH BIGINT NOT NULL,
  CONTENT_TYPE VARCHAR(30) NOT NULL,
  FILE_CREATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ARCHIVE_ID)
);

select * from FILE_VERSION;
select * from FILE_ARCHIVE;